[remote.github]
owner = "overflow65537"
repo = "MFW-Updater"

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat[：:]", group = "新增 | Feat" },
    { message = "^fix[：:]", group = "修复 | Fix" },
    { message = "^docs[：:]", group = "文档 | Docs" },
    { message = "^perf[：:]", group = "优化 | Perf" },
    { message = "^refactor\\(clippy\\)", skip = true },
    { message = "^refactor[：:]", group = "重构 | Refactor" },
    { message = "^style[：:]", group = "样式 | Style" },
    { message = "^test[：:]", group = "测试 | Test" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
    { message = "^chore[：:]", group = "杂项 | Chore" },
    { message = "^other[：:]", group = "其它 | Other" },
    { message = "^ci[：:]", group = "集成 | CI" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
ignore_tags = "rc"
topo_order = false
sort_commits = "newest"
